version: "2.4"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 6.0.0.0/24

services:
  hub1:
    container_name: spn-test-simple-hub1
    hostname: hub1
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub1:ro
      - ${SPN_TEST_DATA_DIR}/hub1:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.11

  hub2:
    container_name: spn-test-simple-hub2
    hostname: hub2
    image: alpine
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub2:ro
      - ${SPN_TEST_DATA_DIR}/hub2:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.12

  hub3:
    container_name: spn-test-simple-hub3
    hostname: hub3
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub3:ro
      - ${SPN_TEST_DATA_DIR}/hub3:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.13

  hub4:
    container_name: spn-test-simple-hub4
    hostname: hub4
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub4:ro
      - ${SPN_TEST_DATA_DIR}/hub4:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.14

  hub5:
    container_name: spn-test-simple-hub5
    hostname: hub5
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub5:ro
      - ${SPN_TEST_DATA_DIR}/hub5:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.15

  hub6:
    container_name: spn-test-simple-hub6
    hostname: hub6
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_OLD_BIN}:/opt/hub6:ro
      - ${SPN_TEST_DATA_DIR}/hub6:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.16

  hub7:
    container_name: spn-test-simple-hub7
    hostname: hub7
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_OLD_BIN}:/opt/hub7:ro
      - ${SPN_TEST_DATA_DIR}/hub7:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.17

  hub8:
    container_name: spn-test-simple-hub8
    hostname: hub8
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_OLD_BIN}:/opt/hub8:ro
      - ${SPN_TEST_DATA_DIR}/hub8:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.18

  hub9:
    container_name: spn-test-simple-hub9
    hostname: hub9
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_OLD_BIN}:/opt/hub9:ro
      - ${SPN_TEST_DATA_DIR}/hub9:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.19

  hub10:
    container_name: spn-test-simple-hub10
    hostname: hub10
    image: toolset.safing.network/dev
    entrypoint: "/opt/shared/entrypoint.sh"
    volumes:
      - ${SPN_TEST_OLD_BIN}:/opt/hub10:ro
      - ${SPN_TEST_DATA_DIR}/hub10:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.20
