#pragma once

#include <stddef.h>

// Authoritative native-layout side of the Rust ABI checks. This header is
// compiled with the same NDIS and KMDF headers as helper.c. Keep it x64/ARM64
// only: those are the two architectures exposed by wdk/build.rs.
#if defined(_WIN64)

#define PM_ABI_ASSERT_IMPL2(condition, line) \
    typedef char pm_abi_assert_##line[(condition) ? 1 : -1]
#define PM_ABI_ASSERT_IMPL(condition, line) PM_ABI_ASSERT_IMPL2(condition, line)
#define PM_ABI_ASSERT(condition) PM_ABI_ASSERT_IMPL(condition, __LINE__)
#define PM_ABI_SIZE(type, size, alignment) \
    PM_ABI_ASSERT(sizeof(type) == (size)); \
    PM_ABI_ASSERT(__alignof(type) == (alignment))
#define PM_ABI_OFFSET(type, field, offset) \
    PM_ABI_ASSERT(offsetof(type, field) == (offset))

PM_ABI_SIZE(BOOLEAN, 1, 1);
PM_ABI_SIZE(KIRQL, 1, 1);
PM_ABI_SIZE(KPROCESSOR_MODE, 1, 1);
PM_ABI_SIZE(HANDLE, 8, 8);
PM_ABI_SIZE(SIZE_T, 8, 8);
PM_ABI_SIZE(NTSTATUS, 4, 4);
PM_ABI_SIZE(ADDRESS_FAMILY, 2, 2);
PM_ABI_SIZE(COMPARTMENT_ID, 4, 4);
PM_ABI_SIZE(GUID, 16, 4);
PM_ABI_SIZE(UNICODE_STRING, 16, 8);
PM_ABI_SIZE(LIST_ENTRY, 16, 8);
PM_ABI_SIZE(IO_STATUS_BLOCK, 16, 8);
PM_ABI_SIZE(EX_RUNDOWN_REF, 8, 8);
PM_ABI_SIZE(EX_SPIN_LOCK, 4, 4);
PM_ABI_SIZE(ERESOURCE, 104, 8);
PM_ABI_SIZE(KQUEUE, 64, 8);
PM_ABI_SIZE(MDL, 48, 8);
PM_ABI_SIZE(DEVICE_OBJECT, 336, 16);
PM_ABI_SIZE(DRIVER_OBJECT, 336, 8);
PM_ABI_SIZE(IRP, 208, 16);
PM_ABI_SIZE(IO_STACK_LOCATION, 72, 8);
PM_ABI_OFFSET(DEVICE_OBJECT, DeviceExtension, 64);
PM_ABI_OFFSET(DRIVER_OBJECT, DriverUnload, 104);
PM_ABI_OFFSET(DRIVER_OBJECT, MajorFunction, 112);
PM_ABI_OFFSET(IRP, AssociatedIrp.SystemBuffer, 24);
PM_ABI_OFFSET(IRP, IoStatus.Status, 48);
PM_ABI_OFFSET(IRP, IoStatus.Information, 56);
PM_ABI_OFFSET(IRP, Tail.Overlay.CurrentStackLocation, 184);
PM_ABI_OFFSET(IO_STACK_LOCATION, Parameters, 8);
PM_ABI_OFFSET(IO_STACK_LOCATION, Parameters.Read.Length, 8);
PM_ABI_OFFSET(IO_STACK_LOCATION, Parameters.Write.Length, 8);
PM_ABI_OFFSET(IO_STACK_LOCATION, Parameters.DeviceIoControl.OutputBufferLength, 8);
PM_ABI_OFFSET(IO_STACK_LOCATION, Parameters.DeviceIoControl.InputBufferLength, 16);
PM_ABI_OFFSET(IO_STACK_LOCATION, Parameters.DeviceIoControl.IoControlCode, 24);
PM_ABI_OFFSET(IO_STACK_LOCATION, Parameters.DeviceIoControl.Type3InputBuffer, 32);
PM_ABI_ASSERT(sizeof(((PIO_STACK_LOCATION)0)->Parameters) == 32);
PM_ABI_ASSERT(sizeof(((PIO_STACK_LOCATION)0)->Parameters.DeviceIoControl) == 32);

PM_ABI_SIZE(WDF_OBJECT_ATTRIBUTES, 56, 8);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, Size, 0);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, EvtCleanupCallback, 8);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, EvtDestroyCallback, 16);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, ExecutionLevel, 24);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, SynchronizationScope, 28);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, ParentObject, 32);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, ContextSizeOverride, 40);
PM_ABI_OFFSET(WDF_OBJECT_ATTRIBUTES, ContextTypeInfo, 48);
PM_ABI_SIZE(WDF_OBJECT_CONTEXT_TYPE_INFO, 40, 8);
PM_ABI_OFFSET(WDF_OBJECT_CONTEXT_TYPE_INFO, Size, 0);
PM_ABI_OFFSET(WDF_OBJECT_CONTEXT_TYPE_INFO, ContextName, 8);
PM_ABI_OFFSET(WDF_OBJECT_CONTEXT_TYPE_INFO, ContextSize, 16);
PM_ABI_OFFSET(WDF_OBJECT_CONTEXT_TYPE_INFO, UniqueType, 24);
PM_ABI_OFFSET(WDF_OBJECT_CONTEXT_TYPE_INFO, EvtDriverGetUniqueContextType, 32);

PM_ABI_SIZE(FWP_BYTE_BLOB, 16, 8);
PM_ABI_OFFSET(FWP_BYTE_BLOB, size, 0);
PM_ABI_OFFSET(FWP_BYTE_BLOB, data, 8);
PM_ABI_SIZE(FWP_VALUE0, 16, 8);
PM_ABI_OFFSET(FWP_VALUE0, type, 0);
PM_ABI_OFFSET(FWP_VALUE0, uint8, 8);
PM_ABI_SIZE(FWP_CONDITION_VALUE0, 16, 8);
PM_ABI_OFFSET(FWP_CONDITION_VALUE0, type, 0);
PM_ABI_OFFSET(FWP_CONDITION_VALUE0, uint8, 8);
PM_ABI_SIZE(FWPM_DISPLAY_DATA0, 16, 8);
PM_ABI_OFFSET(FWPM_DISPLAY_DATA0, name, 0);
PM_ABI_OFFSET(FWPM_DISPLAY_DATA0, description, 8);
PM_ABI_SIZE(FWPM_SESSION0, 72, 8);
PM_ABI_OFFSET(FWPM_SESSION0, flags, 32);
PM_ABI_SIZE(FWPM_SUBLAYER0, 72, 8);
PM_ABI_OFFSET(FWPM_SUBLAYER0, subLayerKey, 0);
PM_ABI_OFFSET(FWPM_SUBLAYER0, displayData, 16);
PM_ABI_OFFSET(FWPM_SUBLAYER0, flags, 32);
PM_ABI_OFFSET(FWPM_SUBLAYER0, providerKey, 40);
PM_ABI_OFFSET(FWPM_SUBLAYER0, providerData, 48);
PM_ABI_OFFSET(FWPM_SUBLAYER0, weight, 64);
PM_ABI_SIZE(FWPM_CALLOUT0, 88, 8);
PM_ABI_OFFSET(FWPM_CALLOUT0, calloutKey, 0);
PM_ABI_OFFSET(FWPM_CALLOUT0, displayData, 16);
PM_ABI_OFFSET(FWPM_CALLOUT0, flags, 32);
PM_ABI_OFFSET(FWPM_CALLOUT0, providerKey, 40);
PM_ABI_OFFSET(FWPM_CALLOUT0, providerData, 48);
PM_ABI_OFFSET(FWPM_CALLOUT0, applicableLayer, 64);
PM_ABI_OFFSET(FWPM_CALLOUT0, calloutId, 80);
PM_ABI_SIZE(FWPM_ACTION0, 20, 4);
PM_ABI_SIZE(FWPM_FILTER0, 200, 8);
PM_ABI_OFFSET(FWPM_FILTER0, layerKey, 64);
PM_ABI_OFFSET(FWPM_FILTER0, subLayerKey, 80);
PM_ABI_OFFSET(FWPM_FILTER0, weight, 96);
PM_ABI_OFFSET(FWPM_FILTER0, numFilterConditions, 112);
PM_ABI_OFFSET(FWPM_FILTER0, filterCondition, 120);
PM_ABI_OFFSET(FWPM_FILTER0, action, 128);
PM_ABI_OFFSET(FWPM_FILTER0, rawContext, 152);
PM_ABI_OFFSET(FWPM_FILTER0, filterId, 176);
PM_ABI_OFFSET(FWPM_FILTER0, effectiveWeight, 184);

PM_ABI_SIZE(FWPS_ACTION0, 8, 4);
PM_ABI_SIZE(FWPS_FILTER_CONDITION0, 24, 8);
PM_ABI_SIZE(FWPS_FILTER3, 64, 8);
PM_ABI_OFFSET(FWPS_FILTER3, filterId, 0);
PM_ABI_OFFSET(FWPS_FILTER3, weight, 8);
PM_ABI_OFFSET(FWPS_FILTER3, subLayerWeight, 24);
PM_ABI_OFFSET(FWPS_FILTER3, flags, 26);
PM_ABI_OFFSET(FWPS_FILTER3, numFilterConditions, 28);
PM_ABI_OFFSET(FWPS_FILTER3, filterCondition, 32);
PM_ABI_OFFSET(FWPS_FILTER3, action, 40);
PM_ABI_OFFSET(FWPS_FILTER3, context, 48);
PM_ABI_OFFSET(FWPS_FILTER3, providerContext, 56);
PM_ABI_SIZE(FWPS_CALLOUT3, 48, 8);
PM_ABI_OFFSET(FWPS_CALLOUT3, calloutKey, 0);
PM_ABI_OFFSET(FWPS_CALLOUT3, flags, 16);
PM_ABI_OFFSET(FWPS_CALLOUT3, classifyFn, 24);
PM_ABI_OFFSET(FWPS_CALLOUT3, notifyFn, 32);
PM_ABI_OFFSET(FWPS_CALLOUT3, flowDeleteFn, 40);
PM_ABI_SIZE(FWPS_INCOMING_VALUE0, 16, 8);
PM_ABI_SIZE(FWPS_INCOMING_VALUES0, 16, 8);
PM_ABI_OFFSET(FWPS_INCOMING_VALUES0, layerId, 0);
PM_ABI_OFFSET(FWPS_INCOMING_VALUES0, valueCount, 4);
PM_ABI_OFFSET(FWPS_INCOMING_VALUES0, incomingValue, 8);
PM_ABI_SIZE(FWPS_CLASSIFY_OUT0, 40, 8);
PM_ABI_OFFSET(FWPS_CLASSIFY_OUT0, actionType, 0);
PM_ABI_OFFSET(FWPS_CLASSIFY_OUT0, outContext, 8);
PM_ABI_OFFSET(FWPS_CLASSIFY_OUT0, filterId, 16);
PM_ABI_OFFSET(FWPS_CLASSIFY_OUT0, rights, 24);
PM_ABI_OFFSET(FWPS_CLASSIFY_OUT0, flags, 28);
PM_ABI_OFFSET(FWPS_CLASSIFY_OUT0, reserved, 32);
PM_ABI_SIZE(FWPS_DISCARD_METADATA0, 16, 8);
PM_ABI_SIZE(FWPS_INBOUND_FRAGMENT_METADATA0, 12, 4);

PM_ABI_SIZE(FWPS_INCOMING_METADATA_VALUES0, 280, 8);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, currentMetadataValues, 0);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, flags, 4);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, reserved, 8);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, discardMetadata, 16);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, flowHandle, 32);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, ipHeaderSize, 40);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, transportHeaderSize, 44);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, processPath, 48);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, token, 56);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, processId, 64);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, sourceInterfaceIndex, 72);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, destinationInterfaceIndex, 76);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, compartmentId, 80);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, fragmentMetadata, 84);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, pathMtu, 96);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, completionHandle, 104);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, transportEndpointHandle, 112);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, remoteScopeId, 120);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, controlData, 128);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, controlDataLength, 136);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, packetDirection, 140);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, headerIncludeHeader, 144);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, headerIncludeHeaderLength, 152);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, destinationPrefix, 156);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, frameLength, 188);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, parentEndpointHandle, 192);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, icmpIdAndSequence, 200);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, localRedirectTargetPID, 204);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, originalDestination, 208);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, redirectRecords, 216);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, currentL2MetadataValues, 224);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, l2Flags, 228);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, ethernetMacHeaderSize, 232);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, wiFiOperationMode, 236);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, vSwitchSourcePortId, 240);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, vSwitchSourceNicIndex, 244);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, vSwitchDestinationPortId, 248);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, vSwitchPacketContext, 256);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, subProcessTag, 264);
PM_ABI_OFFSET(FWPS_INCOMING_METADATA_VALUES0, reserved1, 272);

PM_ABI_SIZE(FWPS_TRANSPORT_SEND_PARAMS1, 48, 8);
PM_ABI_OFFSET(FWPS_TRANSPORT_SEND_PARAMS1, remoteAddress, 0);
PM_ABI_OFFSET(FWPS_TRANSPORT_SEND_PARAMS1, remoteScopeId, 8);
PM_ABI_OFFSET(FWPS_TRANSPORT_SEND_PARAMS1, controlData, 16);
PM_ABI_OFFSET(FWPS_TRANSPORT_SEND_PARAMS1, controlDataLength, 24);
PM_ABI_OFFSET(FWPS_TRANSPORT_SEND_PARAMS1, headerIncludeHeader, 32);
PM_ABI_OFFSET(FWPS_TRANSPORT_SEND_PARAMS1, headerIncludeHeaderLength, 40);
PM_ABI_SIZE(FWPS_STREAM_DATA_OFFSET0, 40, 8);
PM_ABI_OFFSET(FWPS_STREAM_DATA_OFFSET0, netBufferList, 0);
PM_ABI_OFFSET(FWPS_STREAM_DATA_OFFSET0, netBuffer, 8);
PM_ABI_OFFSET(FWPS_STREAM_DATA_OFFSET0, mdl, 16);
PM_ABI_OFFSET(FWPS_STREAM_DATA_OFFSET0, mdlOffset, 24);
PM_ABI_OFFSET(FWPS_STREAM_DATA_OFFSET0, netBufferOffset, 28);
PM_ABI_OFFSET(FWPS_STREAM_DATA_OFFSET0, streamDataOffset, 32);
PM_ABI_SIZE(FWPS_STREAM_DATA0, 64, 8);
PM_ABI_OFFSET(FWPS_STREAM_DATA0, flags, 0);
PM_ABI_OFFSET(FWPS_STREAM_DATA0, dataOffset, 8);
PM_ABI_OFFSET(FWPS_STREAM_DATA0, dataLength, 48);
PM_ABI_OFFSET(FWPS_STREAM_DATA0, netBufferListChain, 56);
PM_ABI_SIZE(FWPS_STREAM_CALLOUT_IO_PACKET0, 40, 8);
PM_ABI_OFFSET(FWPS_STREAM_CALLOUT_IO_PACKET0, streamData, 0);
PM_ABI_OFFSET(FWPS_STREAM_CALLOUT_IO_PACKET0, missedBytes, 8);
PM_ABI_OFFSET(FWPS_STREAM_CALLOUT_IO_PACKET0, countBytesRequired, 16);
PM_ABI_ASSERT(sizeof(((FWPS_STREAM_CALLOUT_IO_PACKET0*)0)->countBytesRequired) == 4);
PM_ABI_OFFSET(FWPS_STREAM_CALLOUT_IO_PACKET0, countBytesEnforced, 24);
PM_ABI_OFFSET(FWPS_STREAM_CALLOUT_IO_PACKET0, streamAction, 32);

PM_ABI_SIZE(NDIS_OBJECT_HEADER, 4, 2);
PM_ABI_ASSERT(MaxNetBufferListInfo == 24);
PM_ABI_SIZE(NET_BUFFER_LIST_POOL_PARAMETERS, 16, 4);
PM_ABI_ASSERT(NDIS_SIZEOF_NET_BUFFER_LIST_POOL_PARAMETERS_REVISION_1 == 16);
PM_ABI_OFFSET(NET_BUFFER_LIST_POOL_PARAMETERS, Header, 0);
PM_ABI_OFFSET(NET_BUFFER_LIST_POOL_PARAMETERS, ProtocolId, 4);
PM_ABI_OFFSET(NET_BUFFER_LIST_POOL_PARAMETERS, fAllocateNetBuffer, 5);
PM_ABI_OFFSET(NET_BUFFER_LIST_POOL_PARAMETERS, ContextSize, 6);
PM_ABI_OFFSET(NET_BUFFER_LIST_POOL_PARAMETERS, PoolTag, 8);
PM_ABI_OFFSET(NET_BUFFER_LIST_POOL_PARAMETERS, DataSize, 12);

PM_ABI_SIZE(NET_BUFFER, 176, 16);
PM_ABI_OFFSET(NET_BUFFER, Next, 0);
PM_ABI_OFFSET(NET_BUFFER, CurrentMdl, 8);
PM_ABI_OFFSET(NET_BUFFER, CurrentMdlOffset, 16);
PM_ABI_OFFSET(NET_BUFFER, DataLength, 24);
PM_ABI_OFFSET(NET_BUFFER, MdlChain, 32);
PM_ABI_OFFSET(NET_BUFFER, DataOffset, 40);
PM_ABI_OFFSET(NET_BUFFER, ChecksumBias, 48);
PM_ABI_OFFSET(NET_BUFFER, Reserved, 50);
PM_ABI_OFFSET(NET_BUFFER, NdisPoolHandle, 56);
PM_ABI_OFFSET(NET_BUFFER, NdisReserved, 64);
PM_ABI_OFFSET(NET_BUFFER, ProtocolReserved, 80);
PM_ABI_OFFSET(NET_BUFFER, MiniportReserved, 128);
PM_ABI_OFFSET(NET_BUFFER, DataPhysicalAddress, 160);
PM_ABI_OFFSET(NET_BUFFER, SharedMemoryInfo, 168);

PM_ABI_SIZE(NET_BUFFER_LIST, 336, 16);
PM_ABI_OFFSET(NET_BUFFER_LIST, Next, 0);
PM_ABI_OFFSET(NET_BUFFER_LIST, FirstNetBuffer, 8);
PM_ABI_OFFSET(NET_BUFFER_LIST, Context, 16);
PM_ABI_OFFSET(NET_BUFFER_LIST, ParentNetBufferList, 24);
PM_ABI_OFFSET(NET_BUFFER_LIST, NdisPoolHandle, 32);
PM_ABI_OFFSET(NET_BUFFER_LIST, NdisReserved, 48);
PM_ABI_OFFSET(NET_BUFFER_LIST, ProtocolReserved, 64);
PM_ABI_OFFSET(NET_BUFFER_LIST, MiniportReserved, 96);
PM_ABI_OFFSET(NET_BUFFER_LIST, Scratch, 112);
PM_ABI_OFFSET(NET_BUFFER_LIST, SourceHandle, 120);
PM_ABI_OFFSET(NET_BUFFER_LIST, NblFlags, 128);
PM_ABI_OFFSET(NET_BUFFER_LIST, ChildRefCount, 132);
PM_ABI_OFFSET(NET_BUFFER_LIST, Flags, 136);
PM_ABI_OFFSET(NET_BUFFER_LIST, Status, 140);
PM_ABI_OFFSET(NET_BUFFER_LIST, NetBufferListInfo, 144);

#undef PM_ABI_OFFSET
#undef PM_ABI_SIZE
#undef PM_ABI_ASSERT
#undef PM_ABI_ASSERT_IMPL
#undef PM_ABI_ASSERT_IMPL2

#endif // defined(_WIN64)
