// Code generated by BobGen sqlite v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Record runs hooks after queries
var _ bob.HookableType = &Record{}
