// Code generated by BobGen sqlite v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Make sure the type Record runs hooks after queries
var _ bob.HookableType = &Record{}
