package geoip

const defaultCountryBasedAccuracy = 200

// AddCountryInfo adds missing country information to the location.
func (l *Location) AddCountryInfo() {
	// Check if we have the country code.
	if l.Country.ISOCode == "" {
		return
	}

	// Get country info.
	info, ok := countries[l.Country.ISOCode]
	if !ok {
		return
	}

	// Add missing data.
	if l.Country.Name == "" {
		l.Country.Name = info.Name
	}
	if l.Coordinates.Latitude == 0 && l.Coordinates.Longitude == 0 {
		l.Coordinates = info.Center
		l.Coordinates.AccuracyRadius = defaultCountryBasedAccuracy
	}
	// TODO: We are currently re-using the Continent-Code for the region. Update this and all dependencies.
	l.Continent.Code = info.Region
}

// GetCountryInfo returns the country info of the given country code, or nil
// in case the data does not exist.
func GetCountryInfo(countryCode string) *CountryInfo {
	info := countries[countryCode]
	return &info
}

// CountryInfo holds additional information about countries.
type CountryInfo struct {
	ID            string
	Name          string
	Region        string
	ContinentCode string
	Center        Coordinates
}

var countries = map[string]CountryInfo{
	"MN": {
		ID:            "MN",
		Name:          "Mongolia",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 46.000000, Longitude: 103.000000},
	},
	"BN": {
		ID:            "BN",
		Name:          "Brunei Darussalam",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 4.000000, Longitude: 114.000000},
	},
	"GI": {
		ID:            "GI",
		Name:          "Gibraltar",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 36.000000, Longitude: -5.000000},
	},
	"SO": {
		ID:            "SO",
		Name:          "Somalia",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 5.000000, Longitude: 46.000000},
	},
	"GG": {
		ID:            "GG",
		Name:          "Guernsey",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 49.000000, Longitude: -2.000000},
	},
	"CL": {
		ID:            "CL",
		Name:          "Chile",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -35.000000, Longitude: -71.000000},
	},
	"LR": {
		ID:            "LR",
		Name:          "Liberia",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 6.000000, Longitude: -9.000000},
	},
	"TZ": {
		ID:            "TZ",
		Name:          "Tanzania",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -6.000000, Longitude: 34.000000},
	},
	"MU": {
		ID:            "MU",
		Name:          "Mauritius",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -20.000000, Longitude: 57.000000},
	},
	"HM": {
		ID:            "HM",
		Name:          "Heard Island and McDonald Islands",
		Region:        "OC-S",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -53.000000, Longitude: 73.000000},
	},
	"AR": {
		ID:            "AR",
		Name:          "Argentina",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -38.000000, Longitude: -63.000000},
	},
	"BV": {
		ID:            "BV",
		Name:          "Bouvet Island",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -54.000000, Longitude: 3.000000},
	},
	"MS": {
		ID:            "MS",
		Name:          "Montserrat",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 16.000000, Longitude: -62.000000},
	},
	"PT": {
		ID:            "PT",
		Name:          "Portugal",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 39.000000, Longitude: -8.000000},
	},
	"BO": {
		ID:            "BO",
		Name:          "Bolivia",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -16.000000, Longitude: -63.000000},
	},
	"VC": {
		ID:            "VC",
		Name:          "Saint Vincent and the Grenadines",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 12.000000, Longitude: -61.000000},
	},
	"RO": {
		ID:            "RO",
		Name:          "Romania",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 45.000000, Longitude: 24.000000},
	},
	"MK": {
		ID:            "MK",
		Name:          "North Macedonia",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 41.000000, Longitude: 21.000000},
	},
	"UG": {
		ID:            "UG",
		Name:          "Uganda",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 1.000000, Longitude: 32.000000},
	},
	"HN": {
		ID:            "HN",
		Name:          "Honduras",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 15.000000, Longitude: -86.000000},
	},
	"IS": {
		ID:            "IS",
		Name:          "Iceland",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 64.000000, Longitude: -19.000000},
	},
	"HR": {
		ID:            "HR",
		Name:          "Croatia",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 45.000000, Longitude: 15.000000},
	},
	"PL": {
		ID:            "PL",
		Name:          "Poland",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 51.000000, Longitude: 19.000000},
	},
	"TC": {
		ID:            "TC",
		Name:          "Turks and Caicos Islands",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 21.000000, Longitude: -71.000000},
	},
	"LC": {
		ID:            "LC",
		Name:          "Saint Lucia",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 13.000000, Longitude: -60.000000},
	},
	"JP": {
		ID:            "JP",
		Name:          "Japan",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 36.000000, Longitude: 138.000000},
	},
	"TN": {
		ID:            "TN",
		Name:          "Tunisia",
		Region:        "AF-N",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 33.000000, Longitude: 9.000000},
	},
	"GS": {
		ID:            "GS",
		Name:          "South Georgia and the South Sandwich Islands",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -54.000000, Longitude: -36.000000},
	},
	"MY": {
		ID:            "MY",
		Name:          "Malaysia",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 4.000000, Longitude: 101.000000},
	},
	"TT": {
		ID:            "TT",
		Name:          "Trinidad and Tobago",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 10.000000, Longitude: -61.000000},
	},
	"BE": {
		ID:            "BE",
		Name:          "Belgium",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 50.000000, Longitude: 4.000000},
	},
	"GU": {
		ID:            "GU",
		Name:          "Guam",
		Region:        "OC-N",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: 13.000000, Longitude: 144.000000},
	},
	"NL": {
		ID:            "NL",
		Name:          "Netherlands",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 52.000000, Longitude: 5.000000},
	},
	"AF": {
		ID:            "AF",
		Name:          "Afghanistan",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 33.000000, Longitude: 67.000000},
	},
	"CK": {
		ID:            "CK",
		Name:          "Cook Islands",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -21.000000, Longitude: -159.000000},
	},
	"PM": {
		ID:            "PM",
		Name:          "Saint Pierre and Miquelon",
		Region:        "NA-N",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 46.000000, Longitude: -56.000000},
	},
	"OM": {
		ID:            "OM",
		Name:          "Oman",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 21.000000, Longitude: 55.000000},
	},
	"NP": {
		ID:            "NP",
		Name:          "Nepal",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 28.000000, Longitude: 84.000000},
	},
	"RS": {
		ID:            "RS",
		Name:          "Serbia",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 44.000000, Longitude: 21.000000},
	},
	"MW": {
		ID:            "MW",
		Name:          "Malawi",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -13.000000, Longitude: 34.000000},
	},
	"NE": {
		ID:            "NE",
		Name:          "Niger",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 17.000000, Longitude: 8.000000},
	},
	"BY": {
		ID:            "BY",
		Name:          "Belarus",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 53.000000, Longitude: 27.000000},
	},
	"TH": {
		ID:            "TH",
		Name:          "Thailand",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 15.000000, Longitude: 100.000000},
	},
	"CW": {
		ID:            "CW",
		Name:          "Curaçao",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 12.000000, Longitude: -68.000000},
	},
	"AS": {
		ID:            "AS",
		Name:          "American Samoa",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -14.000000, Longitude: -170.000000},
	},
	"BF": {
		ID:            "BF",
		Name:          "Burkina Faso",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 12.000000, Longitude: -1.000000},
	},
	"BR": {
		ID:            "BR",
		Name:          "Brazil",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -14.000000, Longitude: -51.000000},
	},
	"CX": {
		ID:            "CX",
		Name:          "Christmas Island",
		Region:        "OC-S",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -10.000000, Longitude: 105.000000},
	},
	"MG": {
		ID:            "MG",
		Name:          "Madagascar",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -18.000000, Longitude: 46.000000},
	},
	"CY": {
		ID:            "CY",
		Name:          "Cyprus",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 35.000000, Longitude: 33.000000},
	},
	"KW": {
		ID:            "KW",
		Name:          "Kuwait",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 29.000000, Longitude: 47.000000},
	},
	"IT": {
		ID:            "IT",
		Name:          "Italy",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 41.000000, Longitude: 12.000000},
	},
	"SJ": {
		ID:            "SJ",
		Name:          "Svalbard and Jan Mayen",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 77.000000, Longitude: 23.000000},
	},
	"ZM": {
		ID:            "ZM",
		Name:          "Zambia",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -13.000000, Longitude: 27.000000},
	},
	"TO": {
		ID:            "TO",
		Name:          "Tonga",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -21.000000, Longitude: -175.000000},
	},
	"EE": {
		ID:            "EE",
		Name:          "Estonia",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 58.000000, Longitude: 25.000000},
	},
	"LI": {
		ID:            "LI",
		Name:          "Liechtenstein",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 47.000000, Longitude: 9.000000},
	},
	"LB": {
		ID:            "LB",
		Name:          "Lebanon",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 33.000000, Longitude: 35.000000},
	},
	"DK": {
		ID:            "DK",
		Name:          "Denmark",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 56.000000, Longitude: 9.000000},
	},
	"LS": {
		ID:            "LS",
		Name:          "Lesotho",
		Region:        "AF-S",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -29.000000, Longitude: 28.000000},
	},
	"CM": {
		ID:            "CM",
		Name:          "Cameroon",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 7.000000, Longitude: 12.000000},
	},
	"BH": {
		ID:            "BH",
		Name:          "Bahrain",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 25.000000, Longitude: 50.000000},
	},
	"NA": {
		ID:            "NA",
		Name:          "Namibia",
		Region:        "AF-S",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -22.000000, Longitude: 18.000000},
	},
	"ZA": {
		ID:            "ZA",
		Name:          "South Africa",
		Region:        "AF-S",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -30.000000, Longitude: 22.000000},
	},
	"PH": {
		ID:            "PH",
		Name:          "Philippines",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 12.000000, Longitude: 121.000000},
	},
	"JM": {
		ID:            "JM",
		Name:          "Jamaica",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -77.000000},
	},
	"PS": {
		ID:            "PS",
		Name:          "Palestine",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 31.000000, Longitude: 35.000000},
	},
	"TM": {
		ID:            "TM",
		Name:          "Turkmenistan",
		Region:        "AS-C",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 38.000000, Longitude: 59.000000},
	},
	"SD": {
		ID:            "SD",
		Name:          "Sudan",
		Region:        "AF-N",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 12.000000, Longitude: 30.000000},
	},
	"KN": {
		ID:            "KN",
		Name:          "Saint Kitts and Nevis",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 17.000000, Longitude: -62.000000},
	},
	"GF": {
		ID:            "GF",
		Name:          "French Guiana",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: 3.000000, Longitude: -53.000000},
	},
	"WS": {
		ID:            "WS",
		Name:          "Samoa",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -13.000000, Longitude: -172.000000},
	},
	"KE": {
		ID:            "KE",
		Name:          "Kenya",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 0.000000, Longitude: 37.000000},
	},
	"CG": {
		ID:            "CG",
		Name:          "Congo",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 0.000000, Longitude: 15.000000},
	},
	"FJ": {
		ID:            "FJ",
		Name:          "Fiji",
		Region:        "OC-C",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -16.000000, Longitude: 179.000000},
	},
	"BL": {
		ID:            "BL",
		Name:          "Saint Barthélemy",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 17.000000, Longitude: -62.000000},
	},
	"TD": {
		ID:            "TD",
		Name:          "Chad",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 15.000000, Longitude: 18.000000},
	},
	"TW": {
		ID:            "TW",
		Name:          "Taiwan",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 23.000000, Longitude: 120.000000},
	},
	"SA": {
		ID:            "SA",
		Name:          "Saudi Arabia",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 23.000000, Longitude: 45.000000},
	},
	"CO": {
		ID:            "CO",
		Name:          "Colombia",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: 4.000000, Longitude: -74.000000},
	},
	"FR": {
		ID:            "FR",
		Name:          "France",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 46.000000, Longitude: 2.000000},
	},
	"WF": {
		ID:            "WF",
		Name:          "Wallis and Futuna",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -13.000000, Longitude: -177.000000},
	},
	"QA": {
		ID:            "QA",
		Name:          "Qatar",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 25.000000, Longitude: 51.000000},
	},
	"IO": {
		ID:            "IO",
		Name:          "British Indian Ocean Territory",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -6.000000, Longitude: 71.000000},
	},
	"LT": {
		ID:            "LT",
		Name:          "Lithuania",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 55.000000, Longitude: 23.000000},
	},
	"IE": {
		ID:            "IE",
		Name:          "Ireland",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 53.000000, Longitude: -8.000000},
	},
	"GW": {
		ID:            "GW",
		Name:          "Guinea-Bissau",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 11.000000, Longitude: -15.000000},
	},
	"PE": {
		ID:            "PE",
		Name:          "Peru",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -9.000000, Longitude: -75.000000},
	},
	"MA": {
		ID:            "MA",
		Name:          "Morocco",
		Region:        "AF-N",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 31.000000, Longitude: -7.000000},
	},
	"CR": {
		ID:            "CR",
		Name:          "Costa Rica",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 9.000000, Longitude: -83.000000},
	},
	"FK": {
		ID:            "FK",
		Name:          "Falkland Islands (Malvinas)",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -51.000000, Longitude: -59.000000},
	},
	"PW": {
		ID:            "PW",
		Name:          "Palau",
		Region:        "OC-N",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: 7.000000, Longitude: 134.000000},
	},
	"NC": {
		ID:            "NC",
		Name:          "New Caledonia",
		Region:        "OC-C",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -20.000000, Longitude: 165.000000},
	},
	"AM": {
		ID:            "AM",
		Name:          "Armenia",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 40.000000, Longitude: 45.000000},
	},
	"CU": {
		ID:            "CU",
		Name:          "Cuba",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 21.000000, Longitude: -77.000000},
	},
	"DE": {
		ID:            "DE",
		Name:          "Germany",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 51.000000, Longitude: 10.000000},
	},
	"MT": {
		ID:            "MT",
		Name:          "Malta",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 35.000000, Longitude: 14.000000},
	},
	"YE": {
		ID:            "YE",
		Name:          "Yemen",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 15.000000, Longitude: 48.000000},
	},
	"BA": {
		ID:            "BA",
		Name:          "Bosnia and Herzegovina",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 43.000000, Longitude: 17.000000},
	},
	"MP": {
		ID:            "MP",
		Name:          "Northern Mariana Islands",
		Region:        "OC-N",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: 17.000000, Longitude: 145.000000},
	},
	"PY": {
		ID:            "PY",
		Name:          "Paraguay",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -23.000000, Longitude: -58.000000},
	},
	"MO": {
		ID:            "MO",
		Name:          "Macao",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 22.000000, Longitude: 113.000000},
	},
	"SH": {
		ID:            "SH",
		Name:          "Saint Helena",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -24.000000, Longitude: -10.000000},
	},
	"PN": {
		ID:            "PN",
		Name:          "Pitcairn",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -24.000000, Longitude: -127.000000},
	},
	"GM": {
		ID:            "GM",
		Name:          "Gambia",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 13.000000, Longitude: -15.000000},
	},
	"TG": {
		ID:            "TG",
		Name:          "Togo",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 8.000000, Longitude: 0.000000},
	},
	"AT": {
		ID:            "AT",
		Name:          "Austria",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 47.000000, Longitude: 14.000000},
	},
	"GT": {
		ID:            "GT",
		Name:          "Guatemala",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 15.000000, Longitude: -90.000000},
	},
	"AE": {
		ID:            "AE",
		Name:          "United Arab Emirates",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 23.000000, Longitude: 53.000000},
	},
	"KR": {
		ID:            "KR",
		Name:          "South Korea",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 35.000000, Longitude: 127.000000},
	},
	"JE": {
		ID:            "JE",
		Name:          "Jersey",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 49.000000, Longitude: -2.000000},
	},
	"LV": {
		ID:            "LV",
		Name:          "Latvia",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 56.000000, Longitude: 24.000000},
	},
	"AW": {
		ID:            "AW",
		Name:          "Aruba",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 12.000000, Longitude: -69.000000},
	},
	"AO": {
		ID:            "AO",
		Name:          "Angola",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -11.000000, Longitude: 17.000000},
	},
	"VE": {
		ID:            "VE",
		Name:          "Venezuela",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: 6.000000, Longitude: -66.000000},
	},
	"AG": {
		ID:            "AG",
		Name:          "Antigua and Barbuda",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 17.000000, Longitude: -61.000000},
	},
	"NU": {
		ID:            "NU",
		Name:          "Niue",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -19.000000, Longitude: -169.000000},
	},
	"KY": {
		ID:            "KY",
		Name:          "Cayman Islands",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 19.000000, Longitude: -80.000000},
	},
	"IM": {
		ID:            "IM",
		Name:          "Isle of Man",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 54.000000, Longitude: -4.000000},
	},
	"FM": {
		ID:            "FM",
		Name:          "Micronesia",
		Region:        "OC-N",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: 7.000000, Longitude: 150.000000},
	},
	"SB": {
		ID:            "SB",
		Name:          "Solomon Islands",
		Region:        "OC-C",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -9.000000, Longitude: 160.000000},
	},
	"LU": {
		ID:            "LU",
		Name:          "Luxembourg",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 49.000000, Longitude: 6.000000},
	},
	"MF": {
		ID:            "MF",
		Name:          "Saint Martin",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -63.000000},
	},
	"AQ": {
		ID:            "AQ",
		Name:          "Antarctica",
		Region:        "AN",
		ContinentCode: "AN",
		Center:        Coordinates{Latitude: -75.000000, Longitude: 0.000000},
	},
	"SC": {
		ID:            "SC",
		Name:          "Seychelles",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -4.000000, Longitude: 55.000000},
	},
	"TL": {
		ID:            "TL",
		Name:          "Timor-Leste",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: -8.000000, Longitude: 125.000000},
	},
	"CC": {
		ID:            "CC",
		Name:          "Cocos (Keeling) Islands",
		Region:        "OC-S",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -12.000000, Longitude: 96.000000},
	},
	"ST": {
		ID:            "ST",
		Name:          "Sao Tome and Principe",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 0.000000, Longitude: 6.000000},
	},
	"NO": {
		ID:            "NO",
		Name:          "Norway",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 60.000000, Longitude: 8.000000},
	},
	"CF": {
		ID:            "CF",
		Name:          "Central African Republic",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 6.000000, Longitude: 20.000000},
	},
	"MR": {
		ID:            "MR",
		Name:          "Mauritania",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 21.000000, Longitude: -10.000000},
	},
	"NI": {
		ID:            "NI",
		Name:          "Nicaragua",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 12.000000, Longitude: -85.000000},
	},
	"AI": {
		ID:            "AI",
		Name:          "Anguilla",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -63.000000},
	},
	"AZ": {
		ID:            "AZ",
		Name:          "Azerbaijan",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 40.000000, Longitude: 47.000000},
	},
	"US": {
		ID:            "US",
		Name:          "United States of America",
		Region:        "NA-N",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 37.000000, Longitude: -95.000000},
	},
	"LA": {
		ID:            "LA",
		Name:          "Lao",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 19.000000, Longitude: 102.000000},
	},
	"BB": {
		ID:            "BB",
		Name:          "Barbados",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 13.000000, Longitude: -59.000000},
	},
	"CD": {
		ID:            "CD",
		Name:          "DR Congo",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -4.000000, Longitude: 21.000000},
	},
	"TK": {
		ID:            "TK",
		Name:          "Tokelau",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -8.000000, Longitude: -171.000000},
	},
	"KZ": {
		ID:            "KZ",
		Name:          "Kazakhstan",
		Region:        "AS-C",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 48.000000, Longitude: 66.000000},
	},
	"DM": {
		ID:            "DM",
		Name:          "Dominica",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 15.000000, Longitude: -61.000000},
	},
	"EG": {
		ID:            "EG",
		Name:          "Egypt",
		Region:        "AF-N",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 26.000000, Longitude: 30.000000},
	},
	"GH": {
		ID:            "GH",
		Name:          "Ghana",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 7.000000, Longitude: -1.000000},
	},
	"BI": {
		ID:            "BI",
		Name:          "Burundi",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -3.000000, Longitude: 29.000000},
	},
	"NZ": {
		ID:            "NZ",
		Name:          "New Zealand",
		Region:        "OC-S",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -40.000000, Longitude: 174.000000},
	},
	"BJ": {
		ID:            "BJ",
		Name:          "Benin",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 9.000000, Longitude: 2.000000},
	},
	"HU": {
		ID:            "HU",
		Name:          "Hungary",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 47.000000, Longitude: 19.000000},
	},
	"BD": {
		ID:            "BD",
		Name:          "Bangladesh",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 23.000000, Longitude: 90.000000},
	},
	"NF": {
		ID:            "NF",
		Name:          "Norfolk Island",
		Region:        "OC-S",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -29.000000, Longitude: 167.000000},
	},
	"LY": {
		ID:            "LY",
		Name:          "Libya",
		Region:        "AF-N",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 26.000000, Longitude: 17.000000},
	},
	"TV": {
		ID:            "TV",
		Name:          "Tuvalu",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -7.000000, Longitude: 177.000000},
	},
	"ZW": {
		ID:            "ZW",
		Name:          "Zimbabwe",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -19.000000, Longitude: 29.000000},
	},
	"NG": {
		ID:            "NG",
		Name:          "Nigeria",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 9.000000, Longitude: 8.000000},
	},
	"GD": {
		ID:            "GD",
		Name:          "Grenada",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 12.000000, Longitude: -61.000000},
	},
	"SM": {
		ID:            "SM",
		Name:          "San Marino",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 43.000000, Longitude: 12.000000},
	},
	"RU": {
		ID:            "RU",
		Name:          "Russian Federation",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 61.000000, Longitude: 105.000000},
	},
	"DZ": {
		ID:            "DZ",
		Name:          "Algeria",
		Region:        "AF-N",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 28.000000, Longitude: 1.000000},
	},
	"DO": {
		ID:            "DO",
		Name:          "Dominican Republic",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -70.000000},
	},
	"SI": {
		ID:            "SI",
		Name:          "Slovenia",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 46.000000, Longitude: 14.000000},
	},
	"BZ": {
		ID:            "BZ",
		Name:          "Belize",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 17.000000, Longitude: -88.000000},
	},
	"DJ": {
		ID:            "DJ",
		Name:          "Djibouti",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 11.000000, Longitude: 42.000000},
	},
	"GN": {
		ID:            "GN",
		Name:          "Guinea",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 9.000000, Longitude: -9.000000},
	},
	"VN": {
		ID:            "VN",
		Name:          "Viet Nam",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 14.000000, Longitude: 108.000000},
	},
	"IR": {
		ID:            "IR",
		Name:          "Iran",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 32.000000, Longitude: 53.000000},
	},
	"KG": {
		ID:            "KG",
		Name:          "Kyrgyzstan",
		Region:        "AS-C",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 41.000000, Longitude: 74.000000},
	},
	"ML": {
		ID:            "ML",
		Name:          "Mali",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 17.000000, Longitude: -3.000000},
	},
	"GP": {
		ID:            "GP",
		Name:          "Guadeloupe",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 16.000000, Longitude: -62.000000},
	},
	"FI": {
		ID:            "FI",
		Name:          "Finland",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 61.000000, Longitude: 25.000000},
	},
	"UA": {
		ID:            "UA",
		Name:          "Ukraine",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 48.000000, Longitude: 31.000000},
	},
	"KP": {
		ID:            "KP",
		Name:          "North Korea (DPRK)",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 40.000000, Longitude: 127.000000},
	},
	"BT": {
		ID:            "BT",
		Name:          "Bhutan",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 27.000000, Longitude: 90.000000},
	},
	"BG": {
		ID:            "BG",
		Name:          "Bulgaria",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 42.000000, Longitude: 25.000000},
	},
	"MM": {
		ID:            "MM",
		Name:          "Myanmar",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 21.000000, Longitude: 95.000000},
	},
	"PK": {
		ID:            "PK",
		Name:          "Pakistan",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 30.000000, Longitude: 69.000000},
	},
	"KI": {
		ID:            "KI",
		Name:          "Kiribati",
		Region:        "OC-N",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -3.000000, Longitude: -168.000000},
	},
	"GL": {
		ID:            "GL",
		Name:          "Greenland",
		Region:        "NA-N",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 71.000000, Longitude: -42.000000},
	},
	"PG": {
		ID:            "PG",
		Name:          "Papua New Guinea",
		Region:        "OC-C",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -6.000000, Longitude: 143.000000},
	},
	"PF": {
		ID:            "PF",
		Name:          "French Polynesia",
		Region:        "OC-E",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -17.000000, Longitude: -149.000000},
	},
	"VU": {
		ID:            "VU",
		Name:          "Vanuatu",
		Region:        "OC-C",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -15.000000, Longitude: 166.000000},
	},
	"HT": {
		ID:            "HT",
		Name:          "Haiti",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -72.000000},
	},
	"SV": {
		ID:            "SV",
		Name:          "El Salvador",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 13.000000, Longitude: -88.000000},
	},
	"EC": {
		ID:            "EC",
		Name:          "Ecuador",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -1.000000, Longitude: -78.000000},
	},
	"KM": {
		ID:            "KM",
		Name:          "Comoros",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -11.000000, Longitude: 43.000000},
	},
	"VI": {
		ID:            "VI",
		Name:          "Virgin Islands (U.S.)",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -64.000000},
	},
	"YT": {
		ID:            "YT",
		Name:          "Mayotte",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -12.000000, Longitude: 45.000000},
	},
	"ET": {
		ID:            "ET",
		Name:          "Ethiopia",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 9.000000, Longitude: 40.000000},
	},
	"JO": {
		ID:            "JO",
		Name:          "Jordan",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 30.000000, Longitude: 36.000000},
	},
	"RE": {
		ID:            "RE",
		Name:          "Réunion",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -21.000000, Longitude: 55.000000},
	},
	"NR": {
		ID:            "NR",
		Name:          "Nauru",
		Region:        "OC-N",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: 0.000000, Longitude: 166.000000},
	},
	"HK": {
		ID:            "HK",
		Name:          "Hong Kong",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 22.000000, Longitude: 114.000000},
	},
	"AU": {
		ID:            "AU",
		Name:          "Australia",
		Region:        "OC-S",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: -25.000000, Longitude: 133.000000},
	},
	"FO": {
		ID:            "FO",
		Name:          "Faroe Islands",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 61.000000, Longitude: -6.000000},
	},
	"IQ": {
		ID:            "IQ",
		Name:          "Iraq",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 33.000000, Longitude: 43.000000},
	},
	"GE": {
		ID:            "GE",
		Name:          "Georgia",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 42.000000, Longitude: 43.000000},
	},
	"UZ": {
		ID:            "UZ",
		Name:          "Uzbekistan",
		Region:        "AS-C",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 41.000000, Longitude: 64.000000},
	},
	"IN": {
		ID:            "IN",
		Name:          "India",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 20.000000, Longitude: 78.000000},
	},
	"MX": {
		ID:            "MX",
		Name:          "Mexico",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 23.000000, Longitude: -102.000000},
	},
	"ER": {
		ID:            "ER",
		Name:          "Eritrea",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 15.000000, Longitude: 39.000000},
	},
	"AL": {
		ID:            "AL",
		Name:          "Albania",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 41.000000, Longitude: 20.000000},
	},
	"GY": {
		ID:            "GY",
		Name:          "Guyana",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: 4.000000, Longitude: -58.000000},
	},
	"CA": {
		ID:            "CA",
		Name:          "Canada",
		Region:        "NA-N",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 56.000000, Longitude: -106.000000},
	},
	"SY": {
		ID:            "SY",
		Name:          "Syrian Arab Republic",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 34.000000, Longitude: 38.000000},
	},
	"SG": {
		ID:            "SG",
		Name:          "Singapore",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 1.000000, Longitude: 103.000000},
	},
	"VG": {
		ID:            "VG",
		Name:          "Virgin Islands (British)",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -64.000000},
	},
	"MC": {
		ID:            "MC",
		Name:          "Monaco",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 43.000000, Longitude: 7.000000},
	},
	"BM": {
		ID:            "BM",
		Name:          "Bermuda",
		Region:        "NA-N",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 32.000000, Longitude: -64.000000},
	},
	"SX": {
		ID:            "SX",
		Name:          "Sint Maarten",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -63.000000},
	},
	"SR": {
		ID:            "SR",
		Name:          "Suriname",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: 3.000000, Longitude: -56.000000},
	},
	"MD": {
		ID:            "MD",
		Name:          "Moldova",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 47.000000, Longitude: 28.000000},
	},
	"CZ": {
		ID:            "CZ",
		Name:          "Czechia",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 49.000000, Longitude: 15.000000},
	},
	"GQ": {
		ID:            "GQ",
		Name:          "Equatorial Guinea",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 1.000000, Longitude: 10.000000},
	},
	"TF": {
		ID:            "TF",
		Name:          "French Southern Territories",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -49.000000, Longitude: 69.000000},
	},
	"CI": {
		ID:            "CI",
		Name:          "Côte d'Ivoire",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 7.000000, Longitude: -5.000000},
	},
	"VA": {
		ID:            "VA",
		Name:          "Holy See",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 41.000000, Longitude: 12.000000},
	},
	"SN": {
		ID:            "SN",
		Name:          "Senegal",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 14.000000, Longitude: -14.000000},
	},
	"PR": {
		ID:            "PR",
		Name:          "Puerto Rico",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 18.000000, Longitude: -66.000000},
	},
	"ID": {
		ID:            "ID",
		Name:          "Indonesia",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 0.000000, Longitude: 113.000000},
	},
	"BS": {
		ID:            "BS",
		Name:          "Bahamas",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 25.000000, Longitude: -77.000000},
	},
	"CV": {
		ID:            "CV",
		Name:          "Cabo Verde",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 16.000000, Longitude: -24.000000},
	},
	"AD": {
		ID:            "AD",
		Name:          "Andorra",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 42.000000, Longitude: 1.000000},
	},
	"SK": {
		ID:            "SK",
		Name:          "Slovakia",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 48.000000, Longitude: 19.000000},
	},
	"MV": {
		ID:            "MV",
		Name:          "Maldives",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 3.000000, Longitude: 73.000000},
	},
	"ME": {
		ID:            "ME",
		Name:          "Montenegro",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 42.000000, Longitude: 19.000000},
	},
	"LK": {
		ID:            "LK",
		Name:          "Sri Lanka",
		Region:        "AS-S",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 7.000000, Longitude: 80.000000},
	},
	"KH": {
		ID:            "KH",
		Name:          "Cambodia",
		Region:        "AS-SE",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 12.000000, Longitude: 104.000000},
	},
	"GR": {
		ID:            "GR",
		Name:          "Greece",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 39.000000, Longitude: 21.000000},
	},
	"SL": {
		ID:            "SL",
		Name:          "Sierra Leone",
		Region:        "AF-W",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 8.000000, Longitude: -11.000000},
	},
	"XK": {
		ID:            "XK",
		Name:          "Kosovo",
		Region:        "EU-E",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 42.000000, Longitude: 20.000000},
	},
	"TJ": {
		ID:            "TJ",
		Name:          "Tajikistan",
		Region:        "AS-C",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 38.000000, Longitude: 71.000000},
	},
	"SE": {
		ID:            "SE",
		Name:          "Sweden",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 60.000000, Longitude: 18.000000},
	},
	"GA": {
		ID:            "GA",
		Name:          "Gabon",
		Region:        "AF-C",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 0.000000, Longitude: 11.000000},
	},
	"UY": {
		ID:            "UY",
		Name:          "Uruguay",
		Region:        "SA",
		ContinentCode: "SA",
		Center:        Coordinates{Latitude: -32.000000, Longitude: -55.000000},
	},
	"MZ": {
		ID:            "MZ",
		Name:          "Mozambique",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -18.000000, Longitude: 35.000000},
	},
	"PA": {
		ID:            "PA",
		Name:          "Panama",
		Region:        "NA-S",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 8.000000, Longitude: -80.000000},
	},
	"SZ": {
		ID:            "SZ",
		Name:          "Eswatini",
		Region:        "AF-S",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -26.000000, Longitude: 31.000000},
	},
	"IL": {
		ID:            "IL",
		Name:          "Israel",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 31.000000, Longitude: 34.000000},
	},
	"GB": {
		ID:            "GB",
		Name:          "United Kingdom",
		Region:        "EU-N",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 55.000000, Longitude: -3.000000},
	},
	"ES": {
		ID:            "ES",
		Name:          "Spain",
		Region:        "EU-S",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 40.000000, Longitude: -3.000000},
	},
	"RW": {
		ID:            "RW",
		Name:          "Rwanda",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -1.000000, Longitude: 29.000000},
	},
	"EH": {
		ID:            "EH",
		Name:          "Western Sahara",
		Region:        "AF-N",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 24.000000, Longitude: -12.000000},
	},
	"MH": {
		ID:            "MH",
		Name:          "Marshall Islands",
		Region:        "OC-N",
		ContinentCode: "OC",
		Center:        Coordinates{Latitude: 7.000000, Longitude: 171.000000},
	},
	"MQ": {
		ID:            "MQ",
		Name:          "Martinique",
		Region:        "NA-E",
		ContinentCode: "NA",
		Center:        Coordinates{Latitude: 14.000000, Longitude: -61.000000},
	},
	"CH": {
		ID:            "CH",
		Name:          "Switzerland",
		Region:        "EU-W",
		ContinentCode: "EU",
		Center:        Coordinates{Latitude: 46.000000, Longitude: 8.000000},
	},
	"CN": {
		ID:            "CN",
		Name:          "China",
		Region:        "AS-E",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 35.000000, Longitude: 104.000000},
	},
	"TR": {
		ID:            "TR",
		Name:          "Turkey",
		Region:        "AS-W",
		ContinentCode: "AS",
		Center:        Coordinates{Latitude: 38.000000, Longitude: 35.000000},
	},
	"BW": {
		ID:            "BW",
		Name:          "Botswana",
		Region:        "AF-S",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: -22.000000, Longitude: 24.000000},
	},
	"SS": {
		ID:            "SS",
		Name:          "South Sudan",
		Region:        "AF-E",
		ContinentCode: "AF",
		Center:        Coordinates{Latitude: 4.000000, Longitude: 31.000000},
	},
}
