// Code generated by BobGen sqlite v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Records = Table[
	recordColumns,
	recordIndexes,
	recordForeignKeys,
	recordUniques,
	recordChecks,
]{
	Schema: "",
	Name:   "records",
	Columns: recordColumns{
		Key: column{
			Name:      "key",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Format: column{
			Name:      "format",
			DBType:    "SMALLINT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Value: column{
			Name:      "value",
			DBType:    "BLOB",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Created: column{
			Name:      "created",
			DBType:    "BIGINT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Modified: column{
			Name:      "modified",
			DBType:    "BIGINT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Expires: column{
			Name:      "expires",
			DBType:    "BIGINT",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Deleted: column{
			Name:      "deleted",
			DBType:    "BIGINT",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Secret: column{
			Name:      "secret",
			DBType:    "BOOLEAN",
			Default:   "FALSE",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Crownjewel: column{
			Name:      "crownjewel",
			DBType:    "BOOLEAN",
			Default:   "FALSE",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: recordIndexes{
		SqliteAutoindexRecords1: index{
			Type: "pk",
			Name: "sqlite_autoindex_records_1",
			Columns: []indexColumn{
				{
					Name:         "key",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_records",
		Columns: []string{"key"},
		Comment: "",
	},

	Comment: "",
}

type recordColumns struct {
	Key        column
	Format     column
	Value      column
	Created    column
	Modified   column
	Expires    column
	Deleted    column
	Secret     column
	Crownjewel column
}

func (c recordColumns) AsSlice() []column {
	return []column{
		c.Key, c.Format, c.Value, c.Created, c.Modified, c.Expires, c.Deleted, c.Secret, c.Crownjewel,
	}
}

type recordIndexes struct {
	SqliteAutoindexRecords1 index
}

func (i recordIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexRecords1,
	}
}

type recordForeignKeys struct{}

func (f recordForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type recordUniques struct{}

func (u recordUniques) AsSlice() []constraint {
	return []constraint{}
}

type recordChecks struct{}

func (c recordChecks) AsSlice() []check {
	return []check{}
}
