// Code generated by BobGen sqlite v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var RecordErrors = &recordErrors{
	ErrUniquePkMainRecords: &UniqueConstraintError{
		schema:  "",
		table:   "records",
		columns: []string{"key"},
		s:       "pk_main_records",
	},
}

type recordErrors struct {
	ErrUniquePkMainRecords *UniqueConstraintError
}
