// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: reporter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReporterServiceClient is the client API for ReporterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReporterServiceClient interface {
	ReportConnection(ctx context.Context, in *ReportConnectionRequest, opts ...grpc.CallOption) (*ReportConnectionRespose, error)
}

type reporterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReporterServiceClient(cc grpc.ClientConnInterface) ReporterServiceClient {
	return &reporterServiceClient{cc}
}

func (c *reporterServiceClient) ReportConnection(ctx context.Context, in *ReportConnectionRequest, opts ...grpc.CallOption) (*ReportConnectionRespose, error) {
	out := new(ReportConnectionRespose)
	err := c.cc.Invoke(ctx, "/safing.portmaster.plugin.proto.ReporterService/ReportConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReporterServiceServer is the server API for ReporterService service.
// All implementations must embed UnimplementedReporterServiceServer
// for forward compatibility
type ReporterServiceServer interface {
	ReportConnection(context.Context, *ReportConnectionRequest) (*ReportConnectionRespose, error)
	mustEmbedUnimplementedReporterServiceServer()
}

// UnimplementedReporterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReporterServiceServer struct {
}

func (UnimplementedReporterServiceServer) ReportConnection(context.Context, *ReportConnectionRequest) (*ReportConnectionRespose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportConnection not implemented")
}
func (UnimplementedReporterServiceServer) mustEmbedUnimplementedReporterServiceServer() {}

// UnsafeReporterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReporterServiceServer will
// result in compilation errors.
type UnsafeReporterServiceServer interface {
	mustEmbedUnimplementedReporterServiceServer()
}

func RegisterReporterServiceServer(s grpc.ServiceRegistrar, srv ReporterServiceServer) {
	s.RegisterService(&ReporterService_ServiceDesc, srv)
}

func _ReporterService_ReportConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServiceServer).ReportConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/safing.portmaster.plugin.proto.ReporterService/ReportConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServiceServer).ReportConnection(ctx, req.(*ReportConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReporterService_ServiceDesc is the grpc.ServiceDesc for ReporterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReporterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "safing.portmaster.plugin.proto.ReporterService",
	HandlerType: (*ReporterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportConnection",
			Handler:    _ReporterService_ReportConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reporter.proto",
}
