name: Angular

on:
  push:
    paths:
      - 'desktop/angular/**'
    branches:
      - master
      - develop

  pull_request:
    paths:
      - 'desktop/angular/**'
    branches:
      - master
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: desktop/angular

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install

    - uses: sibiraj-s/action-eslint@v3
      with:
        annotations: true
        extensions: 'ts,html'
        working-directory: desktop/angular

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build angular projects
      run: earthly --ci --remote-cache=ghcr.io/safing/build-cache --push +angular-ci
